config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # GET localhost:3000/about
  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
    @members = %w[claire toni santi sarah olivier]

    search = params[:member]

    if search
      @members = @members.select do |member|
        member.start_with? search.downcase
      end
    end
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

<p>We are awsome</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

<h2>Who do you want to Contact ? </h2>

<form action="/contact" method="get">
    <label for="member"> Please type a name ... </label>
    <input id="member"
    name= "member"
    type="text"
    value= "<%= params[:member] %>"
    placeholder="Charlie">

    <input type="submit">
</form>
<ol>
  <% @members.each do |member| %>
    <li> <%= member.capitalize %> </li>
  <% end %>
</ol>



<%= link_to "<--  Go back home", root_path%>

app/views/pages/home.html.erb
<h1>This is your home page</h1>

<%= link_to("Contact Us", contact_path) %>